import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Header from '@/ui/header';
import Footer from '@/ui/footer';
import './globals.css';

const MonaSans = localFont({
  src: [
    {
      path: './features/ui/font/MonaSans-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './features/ui/font/MonaSans-Medium.woff2',
      weight: '500',
      style: 'medium',
    },
    {
      path: './features/ui/font/MonaSans-Bold.woff2',
      weight: '700',
      style: 'bold',
    },
    {
      path: './features/ui/font/MonaSansExpanded-Bold.woff2',
      weight: '600',
      style: 'expand-bold',
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={MonaSans.className}>
        <Header />
          <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
